export type AttendanceType = 'WFO' | 'WFH' | 'Dinas Luar';

export type AttendanceStatus =
  | 'Hadir Tepat Waktu'
  | 'Terlambat'
  | 'Izin'
  | 'Sakit'
  | 'Alpha';

export type LeaveType = 
  | 'Cuti Tahunan' 
  | 'Izin Pribadi' 
  | 'Sakit' 
  | 'Cuti Melahirkan' 
  | 'Keperluan Mendesak'
  | 'Izin Datang Terlambat'
  | 'Izin Pulang Awal'
  | 'Izin Dinas Luar';

export type LeaveStatus = 'Menunggu' | 'Disetujui' | 'Ditolak';

export type SystemRole = 'superadmin' | 'admin' | 'karyawan';

export interface ShiftInfo {
  id: string;
  name: string;
  startTime: string; // "08:00"
  endTime: string;   // "17:00"
  lateToleranceMinutes: number; // 15 mins
}

export interface Employee {
  id: string;
  nik: string;
  name: string;
  email: string;
  phone: string;
  department: string;
  role: string;
  systemRole: SystemRole;
  avatarUrl: string;
  shift: ShiftInfo;
  remainingLeaveQuota: number;
}

export interface GeoLocationData {
  latitude: number;
  longitude: number;
  accuracy: number;
  address?: string;
  distanceToOfficeMeters: number;
  isWithinRadius: boolean;
}

export interface AttendanceRecord {
  id: string;
  employeeId: string;
  employeeName: string;
  employeeNik: string;
  department: string;
  date: string; // YYYY-MM-DD
  type: AttendanceType;
  checkInTime: string | null; // "08:12:30"
  checkOutTime: string | null; // "17:05:10"
  status: AttendanceStatus;
  lateMinutes?: number; // Durasi keterlambatan dalam menit (e.g. 30 menit jika jadwal 07:00 dan masuk 07:30)
  earlyMinutes?: number; // Durasi pulang awal dalam menit
  hasLatePermit?: boolean; // Apakah memiliki Izin Datang Terlambat yang disetujui
  hasEarlyPermit?: boolean; // Apakah memiliki Izin Pulang Awal yang disetujui
  checkInPhoto?: string;
  checkOutPhoto?: string;
  location?: GeoLocationData;
  notes?: string;
  isManualEntry?: boolean;
  isAutoGenerated?: boolean;
  recordedBy?: string;
}

export interface LeaveRequest {
  id: string;
  employeeId: string;
  employeeName: string;
  employeeNik: string;
  department: string;
  type: LeaveType;
  startDate: string; // YYYY-MM-DD
  endDate: string;   // YYYY-MM-DD
  totalDays: number;
  estimatedArrivalTime?: string;    // e.g. "09:30" for Izin Datang Terlambat
  lateMinutes?: number;             // e.g. 60 (minutes late)
  estimatedDepartureTime?: string;  // e.g. "15:30" for Izin Pulang Awal
  earlyDepartureMinutes?: number;   // e.g. 120 (minutes earlier than shift end)
  reason: string;
  status: LeaveStatus;
  appliedAt: string;
  approvedBy?: string;
  notes?: string;
}

export interface OfficeConfig {
  name: string;
  address: string;
  latitude: number;
  longitude: number;
  radiusMeters: number;
  workStartTime: string;
  workEndTime: string;
  lateToleranceMinutes: number;
  maxLatePermitCountPerMonth: number;     // Batas frekuensi izin terlambat per bulan (e.g. 3 kali)
  maxLatePermitMinutesPerMonth: number;   // Batas total durasi izin terlambat per bulan (e.g. 120 menit)
  maxEarlyLeaveCountPerMonth: number;     // Batas frekuensi izin pulang awal per bulan (e.g. 3 kali)
  maxEarlyLeaveMinutesPerMonth: number;   // Batas total durasi izin pulang awal per bulan (e.g. 120 menit)
}

export interface FingerprintDevice {
  id: string;
  name: string;
  ipAddress: string; // e.g. "192.168.1.201"
  port: number;      // e.g. 4370
  commKey: string;   // e.g. "0"
  protocol: 'ZKProtocol' | 'ADMS_HTTP' | 'Standalone_TCP';
  location: string;  // e.g. "Lobby Kantor Lantai 1"
  status: 'Online' | 'Offline' | 'Syncing';
  lastSyncAt: string | null;
  totalLogsFetched: number;
  autoSyncIntervalMinutes: number; // e.g. 5
  enabled: boolean;
}

export interface FingerprintPunchLog {
  id: string;
  deviceId: string;
  deviceName: string;
  userPin: string; // NIK or PIN in device
  matchedEmployeeId?: string;
  matchedEmployeeName?: string;
  matchedEmployeeDepartment?: string;
  timestamp: string; // "YYYY-MM-DD HH:mm:ss"
  punchType: 'CheckIn' | 'CheckOut' | 'AutoDetect';
  verifyMethod: 'Fingerprint' | 'Face' | 'RFID' | 'Password';
  syncStatus: 'Synced' | 'Pending' | 'Ignored' | 'EmployeeNotFound';
  syncedAttendanceId?: string;
  notes?: string;
}
